[package]
name = "vfl-cli"
version.workspace = true
edition.workspace = true

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
vfl = { path = "../vfl", features = ["wgpu", "res"] }
