[package]
name = "vfl-cli"
version.workspace = true
edition.workspace = true

[dependencies]
clap = { version = "4", features = ["derive"] }
mesh-tools = "0.3.0"
vfl = { path = "../vfl", features = ["wgpu", "res"] }
num_enum = "0.7.3"
