[workspace]
resolver = "2"
members = [
    # bevy viewer is on the backburner
    # "crates/bevy_viewer",
    "crates/lightweight_viewer",
    "crates/vee_wgpu",
    "crates/vfl",
]

[workspace.dependencies]
vfl = { path = "crates/vfl" }
