[package]
name = "bevy_viewer"
version = "0.1.0"
edition = "2024"

[dependencies]
vfl = { path = "../vfl" }
bevy_egui = "0.34.1"
bevy = { version = "0.16.0", features = ["bevy_picking", "bevy_dev_tools"] }
binrw = "0.15.0"
image = "0.25.6"
futures = "0.3.31"
