[package]
name = "lightweight_viewer"
version = "0.1.0"
edition = "2024"

[dependencies]
pollster = "0.4"
wgpu = "25.0.0"
winit = { version = "0.30.8", features = ["android-native-activity"] }
vfl = { path = "../vfl" }
