[package]
name = "vee"
version = "0.1.0"
edition = "2024"

[dependencies]
binrw = "0.15.0"
flate2 = { version = "1.1.1", features = ["rust_backend"] }
half = "2.6.0"
mesh-tools = { version = "0.1.0", optional = true }

[features]
gltf = ["mesh-tools"]
